version: "3"

services:
  postgres:
    container_name: postgis
    image: postgis/postgis:latest
    env_file: pg_env.txt
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    container_name: inovasiapp
    env_file: .env 
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
    name: postgres_data
 
